[tox]
envlist = py38, py39, py310, lint, type
isolated_build = true

[testenv]
deps =
    pytest>=7.0.0
commands =
    pytest {posargs:tests}

[testenv:lint]
deps =
    flake8>=5.0.0
commands =
    flake8 src/fenestr tests

[testenv:type]
deps =
    mypy>=1.0.0
    ipython>=7.0.0
commands =
    mypy src/fenestr
